-- ANVIX curated global_signals seed (auto-generated by ml/curated_seed.mjs)
-- 31 rows. Idempotent via ON CONFLICT.

INSERT INTO public.global_signals (hash, kind, severity, source, sample_context, report_count)
VALUES
('8a55751ac2c7545c41edc8336aaa7c3cea1bdc967cf67d6e2bd0bcadc69b6870','email','high','curated','FTC bulletin 2025-Q4: fake remote-job offer, requests equipment fee', 3),
('1e0da86ea53a0aa1e751bbf9e89a887e6256535030620b85752a90238c3d46f8','email','high','curated','IC3: unsolicited $85/hr WFH offer, crypto payment', 3),
('550ef62939ac1074d998d0b195e0759898fca4d632c8f9451826f07f3b5f560d','email','high','curated','IC3: fake HR sending on-boarding docs from free mailbox', 3),
('58b2f3166e029a7c517a5d043a0eec00fc7d53c65263336e995076321f6b7956','email','high','curated','FTC scam-job bulletin, target: India tech grads', 3),
('5b8be8b4c7322c311df23e781ca7cab490414e840beb5e0f5a0a460c99914be2','email','critical','curated','Impersonates Amazon recruiter, look-alike domain', 3),
('7cebe91d56b19123ccc6ad4a83f0967ca08181fee6e3dbfd914c8e454fe809bc','email','critical','curated','Impersonates Google recruiter, homoglyph domain', 3),
('5261d1173e230bf286f5f22c23739fbc3823c310739c47adecfc31eb9e67f442','domain','critical','curated','URLhaus: homoglyph phish of amazon.jobs', 3),
('c0d0f07ec0000a948a126b28e2cce31eb64514cf9b23a3992f4aadd9165fcf8b','domain','critical','curated','URLhaus: homoglyph phish of Google careers', 3),
('b0ce62f5a14be14b79531344725e40a1f83b006ea02254a00a9892711a2f4676','domain','high','curated','OpenPhish: fake Meta remote hiring portal', 3),
('0ccdbe5e9b199a8af41a75338dc5595f655d2c17af3615f9143633454191335b','domain','critical','curated','OpenPhish: fake LinkedIn recruiter portal', 3),
('f0e24e98dd3e352ae170906dfd9ce958731b3079f19d7abaf9d05a38441370c7','domain','critical','curated','APWG: credential-harvesting fake MS HR portal', 3),
('3c118d2707b8f5acd3f7c2fe8829ed5b80e5ba7a55281423e90ccb4d2093d1bb','domain','high','curated','URLhaus: fake Workday onboarding domain', 3),
('47f5f4b4ea4bd15e861339a733469252aa1b301fa1c63d69161632fa5c4e8a70','domain','high','curated','Suspicious TLD, credential harvester', 3),
('d7f7622f6b08f379454d78fdb82b05d7483b39cd9ffaa97b68ee8775fb06e149','domain','high','curated','Suspicious TLD used in advance-fee job scams', 3),
('f72cd99be3df24dbe228738cf90a34d64dde101c7b1227208aa79fdca2b2c042','domain','high','curated','OpenPhish: generic recruiter phishing kit', 3),
('bca2e12540efddc0b4f9229ed77b867c1f327174df501d1b71063a0696c92406','domain','warning','curated','Overnight-registered click-TLD, mass-mailed', 3),
('f6b6b9470abf8ba3d06fe99da3d2a3500e65c2bc3badf5c54ec9545c6b084fe7','payment_handle','critical','curated','IC3: BTC address in equipment-fee scam', 3),
('1c35b423215254fb5f8cb1b76777354db7f5500167ce9f68814bb524a7e9a632','payment_handle','critical','curated','Cash App tag used in fake-onboarding scam', 3),
('881b0bd8ad161a2801414890bef39fee3c31d5fb41688dbd07a00cb5e1a01353','payment_handle','critical','curated','Venmo handle in advance-fee scam', 3),
('cac870804abebe5931a660faf7124671d58b2f68b85e5d1ed5015888ca88074e','payment_handle','high','curated','UPI handle in India-targeted job scam', 3),
('7a70ac47c93ce6e56d9c5c29004b7ed21792caa09ac36cbae0b731e5eeada21f','offer_pattern','high','curated','Classic advance-fee opener', 3),
('e7077c1e566cb62380ed7dc7feb551581bdb08bcb1119e070b77f6e8c681169f','offer_pattern','critical','curated','Equipment-fee scam pattern', 3),
('2128bf9b29c591a6f382e281b3f8f9fb0942abaa333f750929cceb604f3a434f','offer_pattern','critical','curated','Crypto advance-fee pattern', 3),
('fe76199d98164b53ad09798bd79f9c17d38e99f2c474b9ceefb9a9c92404e448','offer_pattern','high','curated','Training-fee scam pattern', 3),
('ba53f898d7e05702ed1a8d46a1c4dc4702bcce3a9581b4a6f217cbc4c3f135fa','offer_pattern','high','curated','No-interview red flag', 3),
('a4b3f7e316ab8612f1a426947de934b7211d82d0cc5705be9498a653a5d9857e','offer_pattern','warning','curated','WhatsApp-only HR red flag', 3),
('5bcfc8a3719d3d7fc77ca1d8de60b460b17e991145d1a56a2196b40463f41f5a','recruiter','high','curated','Reused fake recruiter identity, LinkedIn', 3),
('692eaa8dc9270b7f815bbf0b82e6cd9ce6410a5a57b1c6e926b890a86c695430','recruiter','high','curated','Reused fake recruiter identity, Gmail', 3),
('4dd0a3bbef89371a510e644b876c5db5202724852453084c56040f22360ff989','recruiter','warning','curated','Reused fake recruiter identity, India scams', 3),
('f0c46d1be892ad9236922dbb4b51efe4710f9c4df015371a124f47e302b71b0e','phone','high','curated','WhatsApp scam recruiter, India', 3),
('393301aaa0fbb059dc6ccbee1882a47a9b2d2a40d1b16f97c8456e619c9cab30','phone','high','curated','US voice-scam recruiter number', 3)
ON CONFLICT (hash, kind) DO UPDATE SET
  source = EXCLUDED.source,
  sample_context = COALESCE(public.global_signals.sample_context, EXCLUDED.sample_context),
  severity = GREATEST(public.global_signals.severity::text, EXCLUDED.severity::text)::public.signal_severity,
  report_count = GREATEST(public.global_signals.report_count, EXCLUDED.report_count),
  last_seen = now();
